spring:
  application:
    name: bkk-data-crawler
  main:
    banner-mode: "off"
  redis:
    host: localhost
    port: 6379

management:
  server:
    port: 9001
  endpoint:
    health:
      show-details: "ALWAYS"
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8001
  servlet:
    application-display-name: "BKK"
    context-path: /bkk

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: HEADERS

logging:
  level:
    hu:
      oe:
        bakonyi:
          bkk:
            bkkweathercrawler:
              client:
                WeatherClient: DEBUG

scheulder:
  weatherScheduler: "0 0 * ? * *"

weather:
  #bottomLeftLat: 47.1523107
  #bottomLeftLong: 18.8460594
  #topRightLat: 47.6837053
  #topRightLong: 19.391385500000002
  bottomLeftLat: 47.41
  bottomLeftLong: 18.97
  topRightLat: 47.6
  topRightLong: 19.3
  chunkWideSize: 10
  chunkHighSize: 6
  apiUrl: "http://api.openweathermap.org/data/2.5"
  apiKey: "4bd87942ef4b25b2f69f19a086353f49"
  pathToFile: "weatherproperties.json"
  secondaryApiKey: "9deea3d8414e4161803ba12d97024483"
  secondaryBaseUrl: "https://api.weatherbit.io/v2.0"

api:
  key: "2e825506-7aea-4fe1-ad48-5fa87b4ce726"